### ISSUE TITLE
[Bug] : GPT와의 채팅이 나오지않는 버그

### ISSUE THREAD

**Issue by Seobeomsu** [CBNU-SUPER-NOVA/PC_Supporter#30]
## 어떤 버그인가요?

GPT와의 채팅이 나오지않는 버그입니다.

## 어떤 상황에서 발생한 버그인가요?

Windows 환경에서 python 3.12 를 사용하고 openai 1.51.2 버전을 사용중입니다.
이 상태에서 실행 후 새로운 converastion을 생성하고 채팅을 보내면 아래와같은 경고문구가 나오고
gpt의 채팅이 출력이되지않습니다. 

Traceback (most recent call last):
  File "C:\Users\SBS\Desktop\WorkSpace\PC_Supporter\gui\componets\PromptInputPanel.py", line 144, in send_prompt 
    raw_response = send_to_gpt(combined_prompt)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SBS\Desktop\WorkSpace\PC_Supporter\gpt_api\api.py", line 42, in send_to_gpt
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SBS\anaconda3\Lib\site-packages\openai\lib\_old_api.py", line 39, in __call__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1:

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

다음과 같이 위에 openai 버전이 낮아서 함수를 사용할수 없다고 나옵니다.

**Comment by sangjuneeeee** [comment]
꽤 심각한 문제군요

**Comment by sangjuneeeee** [comment]
옛날 버전인 openai.ChatCompletion.create()함수를
openai.chat.completions.create() 함수로 변경하여 해결했습니다.
