### ISSUE TITLE
[Bug] 첫 채팅 시 채팅이 보이지 않는 버그

### ISSUE THREAD

**Issue by sangjuneeeee** [CBNU-SUPER-NOVA/PC_Supporter#42]
## 어떤 버그인가요?

> 어떤 버그인지 간결하게 설명해주세요
처음 프로그램을 실행하고 프롬프트 입력 후 전송시 채팅이 보이지 않는 버그

## 어떤 상황에서 발생한 버그인가요?

> (가능하면) Given-When-Then 형식으로 서술해주세요

처음 프로그램을 실행하고 프롬프트 입력 후 전송시

## 예상 결과

> 예상했던 정상적인 결과가 어떤 것이었는지 설명해주세요

원래는 보여야 하는데 채팅을 새로 만들거나 다른 채팅으로 변경 후 채팅을 하면 정상 작동합니다.

**Comment by Seobeomsu** [comment]
시작할때 conversation 1의 내용을 들어가게 만듬으로써 해결하였습니다.
