### ISSUE TITLE
[Bug] 코드블록 추출

### ISSUE THREAD

**Issue by eunii2** [CBNU-SUPER-NOVA/PC_Supporter#55]
## 어떤 버그인가요?

> Gemini api로 호출되는 경우, 코드 블록 추출을 못함

## 어떤 상황에서 발생한 버그인가요?

> 파일 삭제하는 코드 달라고 했는데, 해당 코드도 그냥 text 내에 포함하여 출력함

## 예상 결과

> text 중간에 코드가 나오면 그 부분에서 코드 블록으로 띄우고 다시 텍스트 출력

**Comment by Seobeomsu** [comment]
bug fixed
