### ISSUE TITLE
[Refact] API 선택 간 개선사항 및 오류

### ISSUE THREAD

**Issue by eunii2** [CBNU-SUPER-NOVA/PC_Supporter#56]
## 어떤 버그인가요?

> Gemini가 디폴트로 되어있으며, gpt api로 바꿔도 적용되지 않음

## 어떤 상황에서 발생한 버그인가요?

> 대화창 생성 전 선택을 했을때에 적용 안됨. 선택을 안하면 디폴트로 Gemini 실행됨

## 예상 결과

> 사용자가 선택을 안한 상태라면 현재 사용 모델이 무엇인지 보여주고, 선택할 수 있도록 유도. Gpt api 선택시 gpt api 정상 호출

## 참고할만한 자료(선택)

**Comment by Seobeomsu** [comment]
DB에 api키 연결기능이 완성되면 실행시의 로직이 바뀔예정이라 수정하지 않고 있습니다.

**Comment by Seobeomsu** [comment]
BugFixed
